# Generated by Django 5.2.1 on 2025-06-21 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='receipt_url',
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hostel_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
