# Generated by Django 5.2.1 on 2025-06-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_paymenthistory_receipt_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostel_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('program', 'level')},
            },
        ),
    ]
