# Generated by Django 5.2.1 on 2025-07-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_programfee"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="hostel_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="other_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="tuition_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
