# Generated by Django 5.2.1 on 2025-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_adminprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
